import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
const mainFont = localFont({src :'./assets/Utendo-ExtraBold.ttf',
                            display:'swap',})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className=" bg-main-bg" lang="en">
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
